{{- if .Values.identity.http.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity.fullname" . }}-secrets
  labels:
    {{- include "identity.labels" . | nindent 4 }}
stringData:
  httpAuthUser: {{ .Values.identity.http.auth.user }}
  httpAuthPassword: {{ .Values.identity.http.auth.password }}
{{- end }}
