apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity.fullname" . }}-secrets
  labels:
    {{- include "identity.labels" . | nindent 4 }}
stringData:
  {{- if .Values.identity.auth.enabled }}
  authUser: {{ .Values.identity.auth.user }}
  authPassword: {{ .Values.identity.auth.password }}
  {{- end }}
  {{- if .Values.identity.db.postgresURI }}
  postgresURI: {{ .Values.identity.db.postgresURI }}
  {{- else if (and .Values.identity.db.mysqlURI .Values.identity.db.milvusURI) }}
  mysqlURI: {{ .Values.identity.db.mysqlURI }}
  milvusURI: {{ .Values.identity.db.milvusURI }}
  {{- end }}
