{{- if .Values.processor.http.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "processor.fullname" . }}-secrets
  labels:
    {{- include "processor.labels" . | nindent 4 }}
stringData:
  httpAuthUser: {{ .Values.processor.http.auth.user }}
  httpAuthPassword: {{ .Values.processor.http.auth.password }}
{{- end }}
